name: CI/CD pipeline for Flask-Speech-APP

on:
    push:
        branches:
            -main
    pull_request:
        branches:
            -main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Test Docker image
              run: |
                docker run -d -p 5000:5000 flask-speech-app 
                sleep 10
                crul http://localhost:5000
                docker stop $(docker ps -q)